server:
  port: 8085
spring:
  application:
    name: payment
#  sleuth:
#    baggage:
#      remote-fields:
#        - payment-id
#      tag-fields:
#        - payment-id
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
