server:
  port: 8081
spring:
  application:
    name: catalog
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/bookstore
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
